<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LabBooking.Domain\LabBooking.Domain.csproj" />
    <ProjectReference Include="..\LabBooking.Application\LabBooking.Application.csproj" />
    <ProjectReference Include="..\LabBooking.Infrastructure.Sqlserver\LabBooking.Infrastructure.Sqlserver.csproj" />
    <ProjectReference Include="..\LabBooking.API\LabBooking.API.csproj" />
  </ItemGroup>

</Project>